sync

diff --git a/bin/git-is-synced b/bin/git-is-synced
--- a/bin/git-is-synced
+++ b/bin/git-is-synced
@@ -1,6 +1,13 @@
 #!/bin/bash
+# Licence: MIT
+# https://github.com/tmewett/my-config/blob/main/bin/git-is-synced
 
 errors=0
+
+if ! type git >/dev/null 2>&1; then
+    echo "'git' not found."
+    exit 1
+fi
 
 # Check if in a Git repository
 if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
